puts "Criando registros de categoria ".ljust(75, "-")
Category.find_or_create_by({ description: "Animais e acessórios" })
Category.find_or_create_by({ description: "Esportes" })
Category.find_or_create_by({ description: "Para a sua casa" })
Category.find_or_create_by({ description: "Eletrônicos e celulares" })
Category.find_or_create_by({ description: "Música e hobbies" })
Category.find_or_create_by({ description: "Bebês e crianças" })
Category.find_or_create_by({ description: "Moda e beleza" })
Category.find_or_create_by({ description: "Veículos e barcos" })
Category.find_or_create_by({ description: "Imóveis" })
Category.find_or_create_by({ description: "Empregos e negócios" })